### ISSUE TITLE
coroutine 'record' was never awaited

### ISSUE THREAD

**Issue by panpansh** [Aureliano90/Futures-Spot-Arbitrage-OKEx-V5#9]
hello, im using the latest version on linux and I get this stdout when I fetch Ticker (5):

```
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/panpansh/Projects/Futures-Spot-Arbitrage-OKEx-V5/src/record.py", line 51, in record_ticker
    loop.run_until_complete(record())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 623, in run_until_complete
    self._check_running()
  File "/usr/lib/python3.9/asyncio/base_events.py", line 583, in _check_running
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
/usr/lib/python3.9/multiprocessing/process.py:331: RuntimeWarning: coroutine 'record' was never awaited
  traceback.print_exc()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

**Comment by Aureliano90** [comment]
I can't reproduce the error. But I guess it's related to `multiprocessing.set_start_method('spawn', True)`. Please try the new commit.

**Comment by panpansh** [comment]
indeed it works, you are frankly good. can I add you somewhere like xmpp or something else ?

**Comment by Aureliano90** [comment]
My Telegram https://t.me/aureliano90.
